# Generated by Django 4.1.3 on 2022-11-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0002_empresa_alter_produto_loja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
