# Generated by Django 4.1.3 on 2022-11-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0005_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosite.empresa'),
        ),
    ]
