# Generated by Django 4.1.3 on 2022-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0007_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='caminho',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
