# Generated by Django 4.1.3 on 2022-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0008_imagem_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='home',
            field=models.BooleanField(default=1),
        ),
    ]
