# Generated by Django 4.1.3 on 2022-11-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0009_produto_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imgpath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
