# Generated by Django 4.1.3 on 2022-11-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0010_produto_imgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imgpath',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='caminho',
            field=models.ImageField(upload_to=''),
        ),
    ]
