# Generated by Django 4.1.3 on 2022-11-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0011_remove_produto_imgpath_alter_imagem_caminho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='caminho',
        ),
        migrations.AddField(
            model_name='imagem',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
