# Generated by Django 4.1.3 on 2022-11-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0012_remove_imagem_caminho_imagem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='ecosite.produto'),
        ),
    ]
